### ISSUE TITLE
Issues running icloud storing data project

### ISSUE THREAD

**Issue by abdulazizalmass** [domenicosolazzo/practice-swift#2]
I am using xcode 6.3

because the app xcode version is 3.2 it has many issues.

Even after doing recommended updates and reading apples documentation.

Please help me
is there a  way to fix this ? 

file directory
icloud/storing data/view controller

**Comment by domenicosolazzo** [comment]
I fixed the project and updated it to Swift 2.0 in master. Let me know if it helps :)

**Comment by abdulazizalmass** [comment]
thanks. 
now it is retrieve data that is has the issue
because store data is connected to retrieve data, retrieve data project would not work properly

**Comment by domenicosolazzo** [comment]
Tried to update all the projects to Swift 2 in the iCloud folder and they should work :) Let me know
